apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo=ghcr.io/jay-2000/devops-gitops-project/devops-demo
    argocd-image-updater.argoproj.io/update-strategy: latest

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-demo

  template:

    metadata:
      labels:
        app: devops-demo

    spec:
      containers:

      - name: devops-demo

        image: ghcr.io/jay-2000/devops-gitops-project/devops-demo:latest

        ports:
        - containerPort: 3000
